In [3]:
from sklearn.datasets import load_digits

In [5]:
import numpy as np
digits = load_digits()
X = np.array(digits.data)
Y = np.array(digits.target)

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [7]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()

In [8]:
reg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [9]:
y_pred = reg.predict(x_test)

In [13]:
import pandas as pd
df = pd.DataFrame({"Actual":list(y_test), "Predicted":list(y_pred)})
df.head(10)

Actual  Predicted
0       1          1
1       5          5
2       0          0
3       7          7
4       1          1
5       0          0
6       6          6
7       1          1
8       5          5
9       4          4

In [15]:
from sklearn import model_selection

kfold = model_selection.KFold(n_splits=10, random_state=7)

result1 = model_selection.cross_val_score(reg, X, Y, cv=kfold, scoring="accuracy")

result1 = result1.sum()/10

result1

0.931530105524519

In [16]:
result2 = model_selection.cross_val_score(reg, X, Y, cv=kfold, scoring="neg_log_loss")

result2 = result2.sum()/10

result2

-0.3442217575018163

In [17]:
result3 = model_selection.cross_val_score(reg, X, Y, cv=kfold, scoring="r2")

result3 = result3.sum()/10

result3

0.8233256404108781

In [18]:
from sklearn import metrics

metrics.mean_squared_error(y_test, y_pred)

0.45

In [19]:
metrics.mean_squared_error(y_test, y_pred)

0.45

In [22]:
from math import sqrt
sqrt(metrics.mean_squared_error(y_test, y_pred))

0.6708203932499369

In [27]:
from sklearn.metrics import classification_report 
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        43
          1       1.00      0.97      0.99        35
          2       1.00      0.97      0.99        36
          3       0.95      0.95      0.95        41
          4       0.97      1.00      0.99        38
          5       0.94      0.97      0.95        30
          6       1.00      1.00      1.00        37
          7       1.00      0.97      0.99        37
          8       0.90      0.93      0.92        29
          9       0.91      0.94      0.93        34

avg / total       0.97      0.97      0.97       360



In [28]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[42  0  0  0  1  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  1  0]
 [ 0  0 35  1  0  0  0  0  0  0]
 [ 0  0  0 39  0  0  0  0  1  1]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  1  0 29  0  0  0  0]
 [ 0  0  0  0  0  0 37  0  0  0]
 [ 0  0  0  0  0  0  0 36  0  1]
 [ 0  0  0  0  0  1  0  0 27  1]
 [ 0  0  0  0  0  1  0  0  1 32]]
