In [38]:
#Question 1 :
import numpy as np
a1 = np.random.random((10,1))
a1


array([[0.46898012],
       [0.49115457],
       [0.42406399],
       [0.15267415],
       [0.57298269],
       [0.50060687],
       [0.22226915],
       [0.04628987],
       [0.0918535 ],
       [0.64839173]])

In [39]:
a1.mean()

0.3619266643546177

In [40]:
#Question 2:
a2 =np.random.random((20,1))
a2

array([[0.05500327],
       [0.85853945],
       [0.66615537],
       [0.72756744],
       [0.84546947],
       [0.97832248],
       [0.1588229 ],
       [0.49703465],
       [0.59115034],
       [0.36068256],
       [0.14293941],
       [0.15958779],
       [0.07335388],
       [0.32522307],
       [0.73838385],
       [0.19359777],
       [0.9978634 ],
       [0.73896479],
       [0.068231  ],
       [0.08198977]])

In [41]:
a2_mean = a2.mean()
mean_array = np.full((20,1),a2_mean)
mean_array

array([[0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413],
       [0.46294413]])

In [42]:
mid = np.subtract(a2,mean_array)
mid

array([[-0.40794086],
       [ 0.39559532],
       [ 0.20321124],
       [ 0.26462331],
       [ 0.38252534],
       [ 0.51537835],
       [-0.30412123],
       [ 0.03409051],
       [ 0.12820621],
       [-0.10226157],
       [-0.32000472],
       [-0.30335634],
       [-0.38959025],
       [-0.13772106],
       [ 0.27543972],
       [-0.26934637],
       [ 0.53491926],
       [ 0.27602065],
       [-0.39471313],
       [-0.38095437]])

In [45]:
z = np.power(mid,2)
z

array([[0.16641575],
       [0.15649566],
       [0.04129481],
       [0.0700255 ],
       [0.14632564],
       [0.26561484],
       [0.09248972],
       [0.00116216],
       [0.01643683],
       [0.01045743],
       [0.10240302],
       [0.09202507],
       [0.15178056],
       [0.01896709],
       [0.07586704],
       [0.07254746],
       [0.28613862],
       [0.0761874 ],
       [0.15579845],
       [0.14512623]])

In [66]:
variance = 0
for i in z:
    variance+= float(i)
variance

2.1435592804859946

In [67]:
deviation= np.power(variance,0.5)
deviation

1.4640899154375713

In [78]:
#Question 3:
arrayA= np.random.random((10,20))
arrayB= np.random.random((20,25))
arrayA
arrayB

array([[0.75424193],
       [0.62011021],
       [0.05007887],
       [0.16463892],
       [0.73697544],
       [0.49514754],
       [0.78520934],
       [0.60393661],
       [0.21786399],
       [0.25277773]])

In [82]:
sum = 0
multiply = np.dot(arrayA, arrayB)
multiply.shape

(10, 25)

In [92]:
#Question 4:
arrayC= np.array([1,2,3,4,5,6,7,8,9,10])
arrayC

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
listA= []
for i in arrayC:
    listA.append(1 / (1 + np.exp(-i)))
newarray= np.array(listA)
newarray

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99752738, 0.99908895, 0.99966465, 0.99987661, 0.9999546 ])