In [33]:
from sklearn.datasets import load_digits

digits = load_digits()
x = digits.data
y = digits.target

In [2]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [5]:
#RBF KERNEL

In [3]:
from sklearn.svm import SVC

rbf = SVC()
rbf.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [4]:
rbf_pred = rbf.predict(x_test)

In [6]:
from sklearn import metrics

print(metrics.confusion_matrix(y_test, rbf_pred))

[[22  0  0  0  0  0  0  0  0  8]
 [ 0 13  0  0  0  0  0  0  0 25]
 [ 0  0 16  0  0  0  0  0  0 18]
 [ 0  0  0 35  0  0  0  0  0  1]
 [ 0  0  0  0 26  0  0  0  0  6]
 [ 0  0  0  0  0 16  0  0  0 26]
 [ 0  0  0  0  0  0 24  0  0 12]
 [ 0  0  0  0  0  0  0 21  0 12]
 [ 0  0  0  1  0  0  0  0  0 44]
 [ 0  0  0  0  0  0  0  0  0 34]]


In [7]:
print(metrics.classification_report(y_test, rbf_pred))

             precision    recall  f1-score   support

          0       1.00      0.73      0.85        30
          1       1.00      0.34      0.51        38
          2       1.00      0.47      0.64        34
          3       0.97      0.97      0.97        36
          4       1.00      0.81      0.90        32
          5       1.00      0.38      0.55        42
          6       1.00      0.67      0.80        36
          7       1.00      0.64      0.78        33
          8       0.00      0.00      0.00        45
          9       0.18      1.00      0.31        34

avg / total       0.80      0.57      0.61       360



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
#POLYNOMIAL KERNEL

In [9]:
poly = SVC(kernel='poly')

poly.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
poly_pred = poly.predict(x_test)
print(metrics.confusion_matrix(y_test, poly_pred))

[[30  0  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0  0 34  0  0  0  0  0  0  0]
 [ 0  0  0 36  0  0  0  0  0  0]
 [ 0  0  0  0 32  0  0  0  0  0]
 [ 0  0  0  0  0 40  0  0  0  2]
 [ 0  0  0  0  0  0 36  0  0  0]
 [ 0  0  0  0  0  0  0 32  0  1]
 [ 0  1  0  0  0  0  0  0 44  0]
 [ 0  0  0  0  0  1  0  0  0 33]]


In [18]:
print(metrics.classification_report(y_test, poly_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        30
          1       0.97      1.00      0.99        38
          2       1.00      1.00      1.00        34
          3       1.00      1.00      1.00        36
          4       1.00      1.00      1.00        32
          5       0.98      0.95      0.96        42
          6       1.00      1.00      1.00        36
          7       1.00      0.97      0.98        33
          8       1.00      0.98      0.99        45
          9       0.92      0.97      0.94        34

avg / total       0.99      0.99      0.99       360



In [ ]:
#SIGMOID KERNEL

In [19]:
sigmoid = SVC(kernel='sigmoid')

sigmoid.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
sigmoid_pred = sigmoid.predict(x_test)
print(metrics.confusion_matrix(y_test, sigmoid_pred))

[[ 0  0  0  0 30  0  0  0  0  0]
 [ 0  0  0  0 38  0  0  0  0  0]
 [ 0  0  0  0 34  0  0  0  0  0]
 [ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0 32  0  0  0  0  0]
 [ 0  0  0  0 42  0  0  0  0  0]
 [ 0  0  0  0 36  0  0  0  0  0]
 [ 0  0  0  0 33  0  0  0  0  0]
 [ 0  0  0  0 45  0  0  0  0  0]
 [ 0  0  0  0 34  0  0  0  0  0]]


In [39]:
print(metrics.classification_report(y_test, sigmoid_pred))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        30
          1       0.00      0.00      0.00        38
          2       0.00      0.00      0.00        34
          3       0.00      0.00      0.00        36
          4       0.09      1.00      0.16        32
          5       0.00      0.00      0.00        42
          6       0.00      0.00      0.00        36
          7       0.00      0.00      0.00        33
          8       0.00      0.00      0.00        45
          9       0.00      0.00      0.00        34

avg / total       0.01      0.09      0.01       360



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
#GAUSSIAN KERNEL

In [42]:
import numpy as np
def my_kernel(X, Y):
     return np.dot(X, Y.T)
    
gauss = SVC(kernel=my_kernel)
gauss.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto',
  kernel=<function my_kernel at 0x0000023B13767158>, max_iter=-1,
  probability=False, random_state=None, shrinking=True, tol=0.001,
  verbose=False)

In [43]:
gauss_pred = gauss.predict(x_test) 

In [44]:
print(metrics.confusion_matrix(y_test, gauss_pred))

[[30  0  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0]
 [ 0  0 34  0  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  1]
 [ 0  0  0  0 32  0  0  0  0  0]
 [ 0  0  0  0  0 41  0  0  0  1]
 [ 0  0  0  0  1  0 35  0  0  0]
 [ 0  0  0  0  1  0  0 31  0  1]
 [ 0  1  1  0  0  1  0  0 42  0]
 [ 0  0  0  0  0  1  0  0  0 33]]


In [45]:
print(metrics.classification_report(y_test, gauss_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        30
          1       0.97      1.00      0.99        38
          2       0.97      1.00      0.99        34
          3       1.00      0.97      0.99        36
          4       0.94      1.00      0.97        32
          5       0.95      0.98      0.96        42
          6       1.00      0.97      0.99        36
          7       1.00      0.94      0.97        33
          8       1.00      0.93      0.97        45
          9       0.92      0.97      0.94        34

avg / total       0.98      0.97      0.98       360

